version: "3"

services:
  mariadb:
    image: mariadb
    container_name: mariadb
    build:
      context: requirements/mariadb
    environment:
      - DB_ROOT=${DB_ROOT}
      - DB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - DB_USER=${DB_USER}
      - DB_USER_PASSWORD=${DB_USER_PASSWORD}
      - DB_NAME=${DB_NAME}
    restart: always
    volumes:
      - database_volume:/var/lib/mysql
    networks:
      - inception_network
  wordpress:
    image: wordpress
    depends_on:
      - mariadb
    container_name: wordpress
    build:
      context: requirements/wordpress
      args:
        - WP_DB_NAME=${WP_DB_NAME}
        - WP_DB_USER=${WP_DB_USER}
        - WP_DB_PASSWORD=${WP_DB_PASSWORD}
        - MYSQL_HOST=${MYSQL_HOST}
        - DOMAIN_NAME=${DOMAIN_NAME}
        - WP_TITLE=${WP_TITLE}
        - WP_ADMIN=${WP_ADMIN}
        - WP_ADMIN_PASSEWORD=${WP_ADMIN_PASSEWORD}
        - WP_ADMIN_EMAIL=${WP_ADMIN_EMAIL}
        - WP_USER=${WP_USER}
        - WP_PASSWORD=${WP_PASSWORD}
    restart: always
    volumes:
      - site_volume:/var/www/html
    networks:
      - inception_network
  nginx:
    image: nginx
    container_name: nginx
    depends_on:
      - wordpress
    build: requirements/nginx
    restart: always
    volumes:
      - site_volume:/var/www/html
    networks:
      - inception_network
    ports:
      - "443:443"

volumes:
    database_volume:
      name: database_volume
      driver: local
      driver_opts:
        o: bind
        type: none
        device: ${VOL_PATH}/db_data
    site_volume:
      name: site_volume
      driver: local
      driver_opts:
        o: bind
        type: none
        device: ${VOL_PATH}/site_data

networks:
  inception_network:
    driver: bridge
