version: '3'


services:
    #front:
    #    build: ./front
    #    ports:
    #        - "3000:3000"
    back:
        image: back
        container_name: back
        build: ./back
        ports:
            - "8080:8080"
        volumes:
            - /home/user42/transcendence/back:/back
        networks:
            - pong_network
    postgres:
        image: postgres
        container_name: postgres
        build: ./postgres
        networks:
            - pong_network
        volumes:
        - ./postgres-entrypoint:/docker-entrypoint-initdb.d
        environment:
            - POSTGRES_USER=root
            - POSTGRES_PASSWORD=imroot
              
        #- ./postgres_data:/var/lib/postgresql/data
      #env_file:
      #- docker.env
      
networks:
    pong_network:
        driver: bridge
